### ISSUE TITLE
standard.go confuses "up" and "down"

### ISSUE THREAD

**Issue by glennhartmann** [BattlesnakeOfficial/rules#18]
The official API reference (https://docs.battlesnake.com/references/api) specifies that positive in the Y axis is "up". However, https://github.com/BattlesnakeOfficial/rules/blob/master/standard.go#L279 is treating "down" as positive in the Y axis.

**Comment by bvanvugt** [comment]
Thanks @glennhartmann - this behaviour is known and, for now, intended. The rules implementation operates on an inverted Y-Axis for in order to support an older version of the game API.

The actual game data that is sent to Battlesnakes uses the coordinate system described in the docs, with "up" being positive Y-Axis - the game engine code manages translating coords based on what API version each Battlesnake is using.

There's a bit more context [here](https://github.com/BattlesnakeOfficial/rules/issues/4) and [here](https://docs.battlesnake.com/guides/migrating-to-api-version-1).

This is a common question, so I'll add something to the README about it :)
