### ISSUE TITLE
Include "last_request_time" in the Game object

### ISSUE THREAD

**Issue by WhiteHalmos** [BattlesnakeOfficial/rules#22]
Background
=========
Currently the Game object contains a `timeout` value:

```json
{
  "id": "totally-unique-game-id",
  "timeout": 500
}
```

It is difficult to measure round trip latency to the Battlesnake server in advance, as it depends on current network conditions.

Thus if a player's server takes 300ms to respond to the request, but network congestion causes an additional 250ms of overhead to be included in the [round-trip time](https://www.cloudflare.com/learning/cdn/glossary/round-trip-time-rtt/), then the snake would time out for this turn (taking a total of 550ms). For subsequent turns, the player's server may continue to time out as from the player's perspective, their code is providing a generous buffer of 200ms compared to the `timeout` value in the Game object. The player's server is also not aware that their previous request timed out.

Proposed addition
==============
A `last_request_time` variable being added to the Game object, included in every request after the first one, which contains the total round-trip time that the previous request took.

First request:
```json
{
  "id": "totally-unique-game-id",
  "timeout": 500
}
```

Response takes 300ms + 50ms of overhead.

Second request:
```json
{
  "id": "totally-unique-game-id",
  "timeout": 500,
  "last_request_time": 350
}
```

Response takes 300ms + 250ms of overhead.

Third request:
```json
{
  "id": "totally-unique-game-id",
  "timeout": 500,
  "last_request_time": 501
}
```

This `last_request_time` value is 501 and not 550 for illustrative purposes as the server should not have to wait for all requests to complete. Otherwise a player whose server crashes and fails to respond will unnecessarily slow down the game.

Other considerations
================
In practice, perhaps an absolute timeout of 750ms (or 1000ms) would be preferable, where if the request's round-trip time took 550ms, its move value would be rejected but `last_request_time` could be accurate up to the absolute timeout.

Example:
A request that takes 550ms would have `last_request_time` set to 550, but a request that takes 1200ms would have its `last_request_time` set to 750ms (whatever the absolute timeout is). That gives the player's server a better chance at reducing processing for subsequent requests to avoid timing out. It also helps the server move on to the next turn at a reasonable pace.

**Comment by bvanvugt** [comment]
@WhiteHalmos thanks so much for writing this up. We were actually in the engine code today so we just went ahead and addressed this. (Albeit we took a different approach than you suggest).

All "Battlesnake" objects now have an additional 'latency' property, which is their roundtrip latency on the previous turn in milliseconds, represented as a string. This is also exactly the same value displayed on the game board during game playback, so a value of "0" indicates a timeout. That behaviour may change later, but it's consistent with what we show in the UI and felt that was important.

We thought it was fair to include it on all Battlesnakes (since the data is public anyway), but I'm open to removing that if you feel there's an advantage there...

[Take a look at the docs and let me know what you think.](https://docs.battlesnake.com/references/api#battlesnake)

**Comment by WhiteHalmos** [comment]
The doc looks great! The way you implemented it is better than my proposal, as now the server has a clear way to signal timeouts without needing to add unnecessary wait time.

Thank you for considering my feedback! I think the data being public is great and fair to everyone. This will help a lot in preventing consecutive timeouts. 👍
