### ISSUE TITLE
StandardRuleset Test Coverage should be 100%

### ISSUE THREAD

**Issue by bvanvugt** [BattlesnakeOfficial/rules#6]
**What is the problem?**
Currently test coverage for standard.go is < 100%

**What is the solution?**
Examine current code coverage stats, and add additional unit tests to cover the missing cases.

**Notes**
We'll also accept PRs that increase code coverage for standard.go without bringing it to 100%.

**Comment by sjbcastro** [comment]
Hi @bvanvugt I've put in a partial pull request for this which increases the code coverage: https://github.com/BattlesnakeOfficial/rules/pull/15

Getting the code coverage up to 100% will involve some rearranging I think, so I've not attempted this yet. For example, there is an early return if maybeSpawnFood returns an error, but because maybeSpawnFood doesn't ever return an error, this a code path which is never exercised.

The way I see it there are a couple of options. You could restructure the error checking so that we have a single return statement at the end; instead of returning early, reverse the if check so we only execute each function if the error is nil. See below:

`
// instead of
err = r.maybeFeedSnakes(nextState)
if err != nil {
	return nil, err
}
err = r.maybeSpawnFood(nextState)

// can do
err = r.maybeFeedSnakes(nextState)
if err == nil {
	err = r.maybeSpawnFood(nextState)
}
`

Alternatively, we could just live with having code coverage below 100%. Really the above is just removing code to artificially increase the code coverage, rather than covering more code paths.

Anyway like I say I've not attempted this yet, figured I would get your take on it first, let me know what you think :)

**Comment by bvanvugt** [comment]
Agreed - let's not restructure code just for coverage stats. Is there any other low-hanging fruit in standard.go, or did you grab it all in #15?

**Comment by sjbcastro** [comment]
Yeah think that makes most sense, it only really risks breaking things for little gain. Had a fresh look at the codecov now that the pull request has gone in, and the rest looks to be in a similar category to the above i.e. there's no legitimate code paths to test any more.

**Comment by bvanvugt** [comment]
👍  thanks for looking into this, going to close the issue. 

As an aside - we're looking for a dev to help us with a slightly larger, very related Go project. If you're interested, shoot me an email at us @ battlesnake.com :)
